### ISSUE TITLE
Soft shadow behind Pat's home page image.

### ISSUE THREAD

**Issue by joelworsham** [realbig/RBM_TH_PATROBERTSON#10]
It's subtle, but in the mock there is a soft drop shadow behind the image. It would need to be created in the PNG image itself, but I think it helps crop out the terrible job I did cutting her image out 😛.

I can quickly supply the image with the shadow if that would help.

<img width="620" alt="screen shot 2016-10-04 at 10 15 48 am" src="https://cloud.githubusercontent.com/assets/4182573/19077678/8b935e90-8a1b-11e6-9115-2949ae781a8b.png">

**Comment by d4mation** [comment]
Ah, you're right. I didn't notice that in the mock before.

This may be possible to do via CSS, but browser support wouldn't be the best. If you happen to have the file with the shadow-ed edge laying around I would appreciate it!

**Comment by joelworsham** [comment]
I'll send over a file

**Comment by joelworsham** [comment]
![pat-headshot-shadow](https://cloud.githubusercontent.com/assets/4182573/19079848/073c8524-8a23-11e6-9348-43535220f5d4.png)

**Comment by d4mation** [comment]
Swapped out the image 👍
