### ISSUE TITLE
Figure out why Archives don't match up with Local Environment

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_PATROBERTSON#11]
After solving #9 and getting it up on Staging, it is ever more frustrating why clearing the Cache doesn't seem to make a difference with the DOM there. The Featured Images don't even show.

Not sure if it is due to how I'm including the templates or what exactly is going on.

Local:

![image](https://cloud.githubusercontent.com/assets/7770631/19091626/65949836-8a51-11e6-8556-74362de7f109.png)

Staging:

![image](https://cloud.githubusercontent.com/assets/7770631/19091641/6e0c017a-8a51-11e6-8477-a370dc13cd99.png)

**Comment by d4mation** [comment]
And this only is a problem on Archive Pages. The Home Page and such properly updates.

**Comment by d4mation** [comment]
Actually, there are some problems on the home page too. Ugh. The files on the server are up to date, so it must be some kind of crazy caching solution in place.

**Comment by joelworsham** [comment]
Have you talked to A2 support about caching stuff? Seems like it's very obtrusive and perhaps it could be "toned down"?

**Comment by joelworsham** [comment]
At least toned down during development

**Comment by d4mation** [comment]
I'm going to try disabling all caching (that I can find/have access to) here in a minute. That way I can ensure that is the problem.

It is odd since the changes to the Archives that the Issue was originally about have been on the server for _days_.

**Comment by joelworsham** [comment]
Yeah... caching can be so wonkey sometimes

**Comment by d4mation** [comment]
Just submitted a support ticket and referenced this Issue. Disabling the caching plugin (and even their "Optimization" plugin which seems to just be a one-stop-shop for activating/deactivating other plugins and configuring their settings) didn't seem to make a difference.

**Comment by d4mation** [comment]
This is still an issue.

I think I've narrowed it down to their caching platform not "understanding" partials.

I've got a basic `archive.php` that pulls in Loop Partials based on the result of `get_post_type()`. I threw a `var_dump()` into the Loop Partial and nothing shows.

**Comment by d4mation** [comment]
Figured it out. Turns out it wasn't (entirely) a caching issue. I had a vestigial `archive-pat-books.php` file on the Server. 😒
