### ISSUE TITLE
Comments associated with wrong user

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_PATROBERTSON#15]
![screenshot 2016-10-27 16 42 04](https://cloud.githubusercontent.com/assets/4993131/19784680/a5c64326-9c64-11e6-86ef-760d05ddce49.png)

😂

**Comment by d4mation** [comment]
😆 😆 😆 

Pretty sure this is because all content got attributed to my user. This is hilarious.

**Comment by d4mation** [comment]
I just went through and re-attributed all content and comments manually via SQL.

```
UPDATE `<prefix>_comments` SET `user_id`=<Pat's User ID> WHERE `user_id`=<My User ID>
UPDATE `<prefix>_posts` SET `post_author`=<Pat's User ID> WHERE `post_author`=<My User ID>
```

Seems to have done the trick 👍
