### ISSUE TITLE
Hamburger menu could use text and has a small target

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_PATROBERTSON#16]
I think if space permits we could append the word "Menu" to the hamburger. Also, it would be nice if the target for clicking it was bigger. Right now it is only the exact dimensions of the 3 lines. It would be better if that entire container it is centered within functioned as a target.

**Comment by d4mation** [comment]
I see what you're saying with adding the "Menu" text there, but with her name right next to it it looks a bit strange:

![image](https://cloud.githubusercontent.com/assets/7770631/19786795/c07404b6-9c6d-11e6-8aff-5c90e0b3c849.png)

![image](https://cloud.githubusercontent.com/assets/7770631/19786826/e24823ce-9c6d-11e6-9ed8-48de50607288.png)

Although it would mean the text would need to be much smaller, as it is only to help contextualize a pretty standard icon maybe something like this would work better?

![image](https://cloud.githubusercontent.com/assets/7770631/19786745/7fae45b8-9c6d-11e6-89ac-957119662f4b.png)

**Comment by joelworsham** [comment]
Could you go with the 1st or 2nd variation and just add a border around it so it looks more button-like and separated? Like (note this is just an example, and not a great one)

![example](https://cloud.githubusercontent.com/assets/4182573/19786964/7b6eff32-9c6e-11e6-9ef3-f39d978119b5.jpg)

**Comment by d4mation** [comment]
That does make it better. I'll admit I didn't style things very much in any of those quick examples. I was doing it partially to to to figure out the spacing necessary for something like this considering her name is right there.

Your suggestion is certainly much more readable though 👍
