### ISSUE TITLE
Home page speaker section text overlapping button on narrow screens

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_PATROBERTSON#18]
![screenshot 2016-10-27 16 54 19](https://cloud.githubusercontent.com/assets/4993131/19785079/163184b2-9c66-11e6-841d-c39fd24c881b.png)

**Comment by d4mation** [comment]
Ah, it looks like this is an iPad bug. Looks fine on a smaller device.

![image](https://cloud.githubusercontent.com/assets/7770631/19785608/015451da-9c68-11e6-881c-83613fae7cfe.png)
