### ISSUE TITLE
Reveal contact form when clicking book me button

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_PATROBERTSON#19]
On the home page, the book me as a speaker button should do something. I think it should reveal a simple contact form. Maybe inline or in a lightbox. Can be the same as the contact page form but perhaps there should be a setting for specifying which form ID.

**Comment by d4mation** [comment]
A lightbox could work. Doing it inline would cause some problems with that area for similar reasons that #18 happened. That section gets all rearranged depending on your screensize so I think a lightbox would be much safer across screen sizes.

**Comment by d4mation** [comment]
Right now it uses the same Contact Form as the Contact Us page, but that can be easily changed without altering the code.

![image](https://cloud.githubusercontent.com/assets/7770631/19819046/c5f90ee6-9d20-11e6-8e15-f9fc6649db4c.png)
