### ISSUE TITLE
Text in main menu shouldn't be black on hover

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_PATROBERTSON#22]
The white on orange looks nice. Black on orange looks immediately like Halloween which I think is the wrong style for Pat. I'd avoid that color combo site wide.

**Comment by d4mation** [comment]
Ah, that was caused by a light/dark check on the Hover Color. It pushed it _just_ over the edge to choose black. I changed it to check against the color before it hovers in that case since it is still readable as white.
