### ISSUE TITLE
Allow control over home page blog section

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_PATROBERTSON#29]
Pat indicated she might want to change which blog post categories show on the home page. Right now it is On life and writings and also Psalms. We need some way to hand over control of that.

**Comment by d4mation** [comment]
Actually made an Issue for this a while back in #3 thinking it may be a desired feature. I'll close that one and we'll track it over here.

**Comment by d4mation** [comment]
This is controlled via Post Meta on the Home Page, as in #3 I decided that Customizer Controls should be for more Global Settings rather than something local to the Home Page.

![image](https://cloud.githubusercontent.com/assets/7770631/20217375/a2e7b254-a7ed-11e6-88a0-46da0290d62d.png)
