### ISSUE TITLE
Modify top home page section

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_PATROBERTSON#31]
The client has decided that they no longer want this section at the top of the home page to showcase a featured book. Instead they just want it to be a sort of welcome section. The main difference is that it doesn't need a button to view more. It should look the same but probably just be managed via the content of the home page. So if she is on the home page and hits Edit Page in the toolbar, she'll get a content area for managing that top section.

@d4mation can you add this to your to-do list for next week?

**Comment by d4mation** [comment]
I think I see what you're saying. It looks like currently she has done something herself using the Books Post Type as if it were a Page or some other Post Meta.

So this would be more-or-less what she'd be looking for (Minus the button)

![image](https://cloud.githubusercontent.com/assets/7770631/23804204/16cb5dc8-0587-11e7-87de-d4edf663acb9.png)

**Comment by brashrebel** [comment]
Yeah. I think it should just be content which she can edit on the home page. That's what she expected when she was poking around and what she wants although not what she asked for. She just wanted the button removed.

**Comment by d4mation** [comment]
All set on her site 👍 

These settings will be available to her when she Edits the Home Page, so if that content ever needs swapper out, it can be done without added non-Books to the Books CPT.
