### ISSUE TITLE
Image not aligning correct on Home Page

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_PATROBERTSON#4]
Seems to be a problem on non-retina displays.

![image](https://cloud.githubusercontent.com/assets/7770631/19037499/956bbf02-8944-11e6-8913-0a6ab4d5e4d7.png)

**Comment by d4mation** [comment]
Present on 1080p screens and possibly other sizes between this and mobile. It does not affect Retina.

Two possible fixes:
1. Change the DOM so it is no longer dependent on the image being above the text on Mobile. The image is being Absolutely positioned on Desktop so that it can peek out the top of that section like in the mocks.
2. Come up with some nasty Media Query to fix the Image Placement for non-retina displays.

**Comment by d4mation** [comment]
Or, I can grab this from the Foundation Docs 😆 

```
$retina: (
  "#{$screen} and (-webkit-min-device-pixel-ratio: 2)",
  "#{$screen} and (min--moz-device-pixel-ratio: 2)",
  "#{$screen} and (-o-min-device-pixel-ratio: 2/1)",
  "#{$screen} and (min-device-pixel-ratio: 2)",
  "#{$screen} and (min-resolution: 192dpi)",
  "#{$screen} and (min-resolution: 2dppx)"
);
```

**Comment by joelworsham** [comment]
Foundation for the win.

**Comment by joelworsham** [comment]
I think this is still in the works, but for me the image isn't sticking to the bottom.

Maybe you could absolute position it to the bottom of the column and then use the equalizer to get the side-by-side columns to be the same height?

<img width="1025" alt="screen shot 2016-10-04 at 10 18 14 am" src="https://cloud.githubusercontent.com/assets/4182573/19077778/e3a7663a-8a1b-11e6-9901-3ebc16f9d19b.png">

**Comment by d4mation** [comment]
I think that may be the solution.

Could you tell me what screen-size/breakpoint you're at there? That way I can ensure that particular appearance won't happen.

**Comment by d4mation** [comment]
I just uploaded some changes to fix this, @joelworsham. I have got the changes in a separate branch locally. It looks really nice on Retina, but still isn't quite what I'd like for non-Retina devices. 

Although, I think this has more to do with the aspect ratio of the screens. My 1080p monitor is much wider than my Macbook's screen. It may be something that is unavoidable. At least it isn't floating out into no-man's land anymore 😛 

Does it look good on your end?

**Comment by d4mation** [comment]
Non-Retina:

![image](https://cloud.githubusercontent.com/assets/7770631/19081556/b0a81204-8a28-11e6-8bb2-08bdbad76c2c.png)

**Comment by d4mation** [comment]
Retina: 

![image](https://cloud.githubusercontent.com/assets/7770631/19081580/c0d3bac0-8a28-11e6-91bd-56d07932749e.png)

**Comment by d4mation** [comment]
Except for on the Staging site, where caching problems over in #11 are causing it to not appear correctly 👎
