### ISSUE TITLE
Make "About" text on homepage typical paragraph size.

### ISSUE THREAD

**Issue by joelworsham** [realbig/RBM_TH_PATROBERTSON#6]
Per the mock, I like having the blockquote emphasized and larger, but I feel like the About text should read the same as normal sized text, based on it's implied prevalence in the content hierarchy.

**Comment by d4mation** [comment]
I agree. I bumped up the size due to some issues with getting the image quite right in that location (As the text needed to span so many lines, like in the mock), but considering #4 this could be a good time to get this fixed.

**Comment by joelworsham** [comment]
Cool!
