### ISSUE TITLE
Footer menu links not underlined.

### ISSUE THREAD

**Issue by joelworsham** [realbig/RBM_TH_PATROBERTSON#7]
I feel like them being linked is assumed. I don't really love how the underline looks, it looks busy.

Thoughts?

**Comment by d4mation** [comment]
I'm not a big fan either, it is just some general styling I tend to include. I've had clients in the past go "Where are the links?" even though they are clearly a different color or something from the main content but they weren't underlined.

I'll set it so any links in the footer don't have `text-decoration: underline` 👍
