### ISSUE TITLE
Make header image shrink drastically on non-home-pages

### ISSUE THREAD

**Issue by joelworsham** [realbig/RBM_TH_PATROBERTSON#8]
Per the original mocks, I think it would be best if the large header image shrunk on all sub-pages, and the tagline disappeared. I think it works on the homepage, being introductory, but it can just become a nuisance on sub-pages, where users likely just want to get to the content.

<img width="789" alt="screen shot 2016-10-04 at 10 08 47 am" src="https://cloud.githubusercontent.com/assets/4182573/19077417/951a3e08-8a1a-11e6-9526-4390f2e82d81.png">

**Comment by joelworsham** [comment]
NOTE: In that mock, a sidebar was never finished. See #9 for more details.

**Comment by d4mation** [comment]
I am pretty sure that on the test/staging site the header should be completely disappearing now? I uploaded a small change yesterday per #5.

The mocks I had were only for the Home Page, so anything on interior pages was kept pretty basic figuring it would be iterated on.

**Comment by joelworsham** [comment]
Oh I didn't see that issue because it's closed. Gotcha. I'm looking at this page right now: http://patrici5.wwwss31.a2hosted.com/about/

And the only other mock was the super basic sub-page, not really too useful anyways.

<img width="1432" alt="screen shot 2016-10-04 at 10 11 31 am" src="https://cloud.githubusercontent.com/assets/4182573/19077513/f1723b24-8a1a-11e6-828b-fef0aaa50609.png">

**Comment by d4mation** [comment]
That's so odd. I purged all the caches (That I could find) and the Header Image still shows like that when I'm logged out. However, when I'm logged in it is gone on interior pages.

**Comment by d4mation** [comment]
Actually, it is gone for me now while being logged out. I guess it is a slower process than on WP Engine.

Could you check on that for me on your end when you get the chance?

**Comment by joelworsham** [comment]
All gone!
